const PAGE_META={dashboard:['Главная','Ваш рабочий центр и контроль сроков'],tasks:['Задачи','Все поручения и сроки в одном списке'],telegram:['Telegram-входящие','Будущий автоматический разбор разрешённых чатов'],assistant:['ИИ-помощник','Планирование, анализ и рабочие решения'],notifications:['Уведомления','Push, Telegram-резерв и история событий'],schedule:['Расписание','Ваш рабочий график по двум заведениям'],settings:['Настройки','Уведомления, интеграции и самостоятельность агента']};
const DEFAULT_TASKS=[{id:'coffee-report',title:'Подготовить отчёт по ревизии кофе',description:'Сравнить с прошлой неделей и отправить руководителю',venue:'Современник',status:'work',priority:'critical',deadline:'2026-07-29T18:00',source:'Вручную',createdAt:'2026-07-29T09:00'},{id:'beer-analysis',title:'Проанализировать безалкогольное пиво',description:'Продажи, остатки и решение по ассортименту',venue:'Оксфорд',status:'new',priority:'high',deadline:'2026-07-31T18:00',source:'Telegram',createdAt:'2026-07-29T10:06'},{id:'supplier-prices',title:'Получить обновлённый прайс поставщика',description:'Поставщик обещал прислать новые цены',venue:'Оба',status:'waiting',priority:'normal',deadline:'2026-07-30T14:00',source:'Telegram',createdAt:'2026-07-27T12:00'},{id:'beer-expiry',title:'Проверить сроки годности кег',description:'Выделить позиции с остаточным сроком менее 30 и 60 дней',venue:'Оксфорд',status:'new',priority:'normal',deadline:'2026-08-01T16:00',source:'Регулярная',createdAt:'2026-07-28T09:00'},{id:'milk-writeoff',title:'Проверить утренние списания молока и сиропов',description:'Сверить сообщения в рабочем чате',venue:'Современник',status:'done',priority:'normal',deadline:'2026-07-29T11:00',source:'Telegram',createdAt:'2026-07-29T08:00'}];
const INBOX=[{title:'Анализ безалкогольного пива',venue:'Оксфорд',deadline:'Пятница, 31 июля',result:'Решение, какие позиции оставить в ассортименте',plan:['Получить продажи за выбранный период','Добавить текущие остатки','Рассчитать оборачиваемость','Подготовить рекомендации']},{title:'Списание St. Peter’s Plum Porter',venue:'Оксфорд',deadline:'Зафиксировано сегодня',result:'Добавить 2 бутылки в журнал списаний с причиной «повреждение этикетки»',plan:['Проверить наличие фотографии','Подтвердить количество','Добавить запись в месячный отчёт']},{title:'Заготовка малинового кордиала',venue:'Современник',deadline:'Приготовлено сегодня',result:'Зафиксировать 4 литра заготовки и место хранения',plan:['Проверить срок годности','Добавить ответственного сотрудника','Сохранить запись в журнале заготовок']},{title:'Сравнение прайсов поставщика',venue:'Оба заведения',deadline:'Срок не указан',result:'Сравнить новый прайс с предыдущим и выделить изменения',plan:['Загрузить оба прайса','Сопоставить одинаковые позиции','Рассчитать изменение цен','Подготовить краткий вывод']}];
let tasks=loadTasks();let currentFilter='all';let currentSearch='';
function loadTasks(){try{const value=JSON.parse(localStorage.getItem('barManagerTasks'));return Array.isArray(value)&&value.length?value:DEFAULT_TASKS}catch{return DEFAULT_TASKS}}
function saveTasks(){localStorage.setItem('barManagerTasks',JSON.stringify(tasks))}
function showToast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2300)}
function navigate(page){document.querySelectorAll('.page').forEach(el=>el.classList.remove('active'));document.getElementById(page)?.classList.add('active');document.querySelectorAll('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===page));document.getElementById('pageTitle').textContent=PAGE_META[page][0];document.getElementById('pageSubtitle').textContent=PAGE_META[page][1];window.scrollTo({top:0,behavior:'smooth'});if(page==='tasks')renderTasks()}
document.querySelectorAll('[data-page]').forEach(btn=>btn.addEventListener('click',()=>navigate(btn.dataset.page)));document.querySelectorAll('[data-go]').forEach(btn=>btn.addEventListener('click',()=>navigate(btn.dataset.go)));
function statusName(status){return{new:'Новая',work:'В работе',waiting:'Ожидаю',done:'Выполнена'}[status]||status}
function venueClass(venue){return venue==='Оксфорд'?'oxford':venue==='Современник'?'sov':''}
function formatDate(value){if(!value)return'Без срока';const date=new Date(value);if(Number.isNaN(date.getTime()))return value;return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(date)}
function isToday(value){if(!value)return false;const d=new Date(value),n=new Date();return d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth()&&d.getDate()===n.getDate()}
function isOverdue(task){return task.status!=='done'&&task.deadline&&new Date(task.deadline).getTime()<Date.now()}
function filteredTasks(){return tasks.filter(task=>{const matchSearch=(task.title+' '+task.description+' '+task.venue).toLowerCase().includes(currentSearch.toLowerCase());let matchFilter=true;if(currentFilter==='today')matchFilter=isToday(task.deadline);else if(currentFilter==='work')matchFilter=task.status==='work'||task.status==='new';else if(currentFilter==='waiting')matchFilter=task.status==='waiting';else if(currentFilter==='done')matchFilter=task.status==='done';return matchSearch&&matchFilter})}
function renderDashboard(){const active=tasks.filter(t=>t.status!=='done').sort((a,b)=>new Date(a.deadline||'2999')-new Date(b.deadline||'2999'));document.getElementById('todayCount').textContent=tasks.filter(t=>isToday(t.deadline)&&t.status!=='done').length;document.getElementById('overdueCount').textContent=tasks.filter(isOverdue).length;document.getElementById('waitingCount').textContent=tasks.filter(t=>t.status==='waiting').length;document.getElementById('dashboardTasks').innerHTML=active.slice(0,4).map(task=>`<div class="task"><button class="check ${task.status==='done'?'done':''}" data-toggle="${task.id}" aria-label="Изменить статус"></button><div><strong>${escapeHtml(task.title)}</strong><div class="meta"><span class="tag ${venueClass(task.venue)}">${escapeHtml(task.venue)}</span><span class="tag ${isOverdue(task)?'urgent':''}">${isOverdue(task)?'Просрочено':formatDate(task.deadline)}</span></div></div><div class="task-time">${statusName(task.status)}</div></div>`).join('')||'<div class="result">Активных задач нет.</div>';bindTaskActions()}
function renderTasks(){document.getElementById('taskRows').innerHTML=filteredTasks().map(task=>`<div class="trow"><div class="title"><strong>${escapeHtml(task.title)}</strong><small>${escapeHtml(task.description||'Без дополнительного описания')}</small></div><div><span class="tag ${venueClass(task.venue)}">${escapeHtml(task.venue)}</span></div><div><button class="status ${task.status}" data-cycle="${task.id}">${statusName(task.status)}</button></div><div>${formatDate(task.deadline)}</div><div>${escapeHtml(task.source||'Вручную')}</div></div>`).join('')||'<div style="padding:24px;color:var(--muted)">По выбранным условиям задач нет.</div>';bindTaskActions();renderDashboard()}
function bindTaskActions(){document.querySelectorAll('[data-toggle]').forEach(btn=>btn.onclick=()=>toggleTask(btn.dataset.toggle));document.querySelectorAll('[data-cycle]').forEach(btn=>btn.onclick=()=>cycleTask(btn.dataset.cycle))}
function toggleTask(id){const task=tasks.find(t=>t.id===id);if(!task)return;task.status=task.status==='done'?'work':'done';saveTasks();renderTasks();showToast(task.status==='done'?'Задача выполнена':'Задача возвращена в работу')}
function cycleTask(id){const order=['new','work','waiting','done'];const task=tasks.find(t=>t.id===id);if(!task)return;task.status=order[(order.indexOf(task.status)+1)%order.length];saveTasks();renderTasks();showToast(`Статус: ${statusName(task.status)}`)}
document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{currentFilter=btn.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===btn));renderTasks()}));document.getElementById('taskSearch').addEventListener('input',e=>{currentSearch=e.target.value;renderTasks()});
const modal=document.getElementById('taskModal');document.querySelectorAll('[data-open-task]').forEach(btn=>btn.addEventListener('click',()=>modal.classList.add('open')));document.getElementById('closeModal').onclick=()=>modal.classList.remove('open');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
document.getElementById('taskForm').addEventListener('submit',e=>{e.preventDefault();const title=document.getElementById('taskTitle').value.trim();if(!title)return;tasks.unshift({id:`task-${Date.now()}`,title,description:document.getElementById('taskDescription').value.trim(),venue:document.getElementById('taskVenue').value,status:document.getElementById('taskStatus').value,priority:document.getElementById('taskPriority').value,deadline:document.getElementById('taskDeadline').value,source:'Вручную',createdAt:new Date().toISOString()});saveTasks();e.target.reset();modal.classList.remove('open');renderTasks();showToast('Задача создана и сохранена на устройстве')});
document.getElementById('aiDraft').onclick=()=>{const title=document.getElementById('taskTitle');const desc=document.getElementById('taskDescription');if(!title.value)title.value='Проанализировать рабочее поручение';if(!desc.value)desc.value='ИИ-разбор будет подключён после настройки OpenAI API. Сейчас создан демонстрационный черновик.';showToast('Подготовлен демонстрационный черновик')};
function renderInbox(index=0){const item=INBOX[index];document.getElementById('analysisPanel').innerHTML=`<div class="eyebrow">ИИ-разбор</div><h3>${escapeHtml(item.title)}</h3><div class="box"><label>Заведение</label><strong>${escapeHtml(item.venue)}</strong></div><div class="box"><label>Срок</label><strong>${escapeHtml(item.deadline)}</strong></div><div class="box"><label>Ожидаемый результат</label><strong>${escapeHtml(item.result)}</strong></div><div class="box"><label>Предлагаемый план</label><ol>${item.plan.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ol></div><div style="display:grid;gap:8px"><button class="btn primary" id="confirmInbox">Подтвердить</button><button class="btn ghost" id="reviewInbox">Требует проверки</button></div>`;document.getElementById('confirmInbox').onclick=()=>showToast('Запись подтверждена в демонстрационном режиме');document.getElementById('reviewInbox').onclick=()=>showToast('Сообщение отправлено на ручную проверку')}
document.querySelectorAll('[data-inbox]').forEach(el=>el.addEventListener('click',()=>{document.querySelectorAll('[data-inbox]').forEach(x=>x.classList.remove('active'));el.classList.add('active');renderInbox(Number(el.dataset.inbox))}));
function addMessage(text,type='user'){const box=document.createElement('div');box.className=`msg ${type}`;box.textContent=text;document.getElementById('messages').appendChild(box);box.scrollIntoView({behavior:'smooth',block:'end'})}
function assistantReply(text){const q=text.toLowerCase();if(q.includes('сегодня'))return'Сегодня приоритетны: отчёт по ревизии кофе, разбор нового поручения по безалкогольному пиву и проверка ответа поставщика. Сначала завершите отчёт с ближайшим сроком.';if(q.includes('потер')||q.includes('риск')||q.includes('проср'))return'Риск сейчас один: задача по отчёту имеет ближайший срок. Также стоит уточнить период анализа безалкогольного пива и поставить дату повторной проверки ответа поставщика.';if(q.includes('telegram')||q.includes('телеграм'))return'В демонстрационных входящих обнаружены: одна новая задача, одно списание и одна заготовка. Для реальной обработки нужно подключить Telegram Bot API и белый список чатов.';if(q.includes('отч'))return'Я подготовлю отчёт после подключения источника данных или загрузки файла. В рабочей версии сначала проверю период, показатели и требуемый формат результата.';return'Принял запрос. В рабочей версии я сначала найду данные в задачах, Telegram и файлах, затем задам только недостающие уточнения и предложу конкретный план действий.'}
function sendAssistant(){const input=document.getElementById('assistantInput');const text=input.value.trim();if(!text)return;addMessage(text);input.value='';setTimeout(()=>addMessage(assistantReply(text),'ai'),250)}
document.getElementById('sendAssistant').onclick=sendAssistant;document.getElementById('assistantInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendAssistant()}});document.querySelectorAll('[data-prompt]').forEach(btn=>btn.addEventListener('click',()=>{navigate('assistant');document.getElementById('assistantInput').value=btn.dataset.prompt;sendAssistant()}));document.querySelectorAll('[data-answer]').forEach(btn=>btn.addEventListener('click',()=>{addMessage(`Уточнение: ${btn.dataset.answer}`);setTimeout(()=>addMessage('Уточнение сохранено. Я обновил бы карточку задачи и план анализа.','ai'),200)}));
document.getElementById('markRead').onclick=()=>{document.querySelectorAll('.notification').forEach(x=>x.classList.remove('unread'));document.getElementById('unreadCount').textContent='0';showToast('Все уведомления отмечены прочитанными')};
async function requestNotifications(){if(!('Notification'in window)){showToast('Браузер не поддерживает уведомления');return false}const permission=await Notification.requestPermission();if(permission==='granted'){showToast('Разрешение на уведомления получено');return true}showToast('Уведомления не разрешены');return false}
async function demoNotification(){const ok=Notification.permission==='granted'||await requestNotifications();if(!ok)return;if(navigator.serviceWorker){const registration=await navigator.serviceWorker.ready;registration.showNotification('Бар-менеджер AI',{body:'Тест: напоминание о задаче работает на этом устройстве.',icon:'./icon.svg',badge:'./icon.svg',tag:'demo-notification',data:{url:'./'}})}else new Notification('Бар-менеджер AI',{body:'Тестовое напоминание'})}
document.getElementById('requestPush').onclick=requestNotifications;document.getElementById('notifyTest').onclick=demoNotification;document.querySelectorAll('[data-switch]').forEach(btn=>btn.onclick=()=>{btn.classList.toggle('on');showToast('Настройка сохранена локально')});document.getElementById('editSchedule').onclick=()=>showToast('Редактор расписания будет добавлен на следующем этапе');
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}))}
renderInbox(0);renderTasks();